### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basileLeroy** [JosueSalazaku/sass-06#1]
# Feedback

## Technical
I saw that you made use of "red" and "blue" classes to create your result. unfortunately, the goal was to not change any html (except for the style links in your <head> element.

Since I don't have access to the SCSS files for "red" and "blue", I can't give any feedback on that content, but I will give you some pointers as to how you could have done it.

Here are a couple of pointers:

in general when working with SCSS it is a good practice to use the nesting overall
```scss
body {
    section {
        pre {
            ...
        }
    }
}
``` 
This allows us to have a clearer view of where the elements are located. 

Then once that is done, we have our basic layout. In your project you created a "default" scss file, but our style.scss can take up that role in the project.

Now that we have a default style.scss we can link the pages (red and blue) to their own css files.

Each of the color pages can now "use" the style.scss and we only need to overwrite certain elements:
```scss
// Example BLUE.SCSS file
@use 'style';

body {
    h1,h4,h6 {
        color: blue;
    }
    pre {
        color: blue;
    }
}
```

## GIT
Well done!
